project_id = "qzsvcqnylqgbzdahskcm"

[functions.analyze-post]
verify_jwt = true

[functions.recategorize-posts]
verify_jwt = true

[functions.format-post]
verify_jwt = true

[functions.discovery-ai]
verify_jwt = true
